### ISSUE TITLE
Is there any tools to keep update with the original spec?

### ISSUE THREAD

**Issue by harttle** [momdo/momdo.github.io#88]
I'm trying to translate whatwg/html into Chinese, during which I find it's really hard to keep updated. Basically, I need:

* The document on which the volunteers (me, for example) translate should be small pieces of the full document.
* Being able to merge the additions from the original document into the translated one.

Did you split the `source` file and build them into `/html/` directory, or just translate on the result html?

**Comment by momdo** [comment]
>Did you split the source file and build them into /html/ directory, or just translate on the result html?

I use result html. About translation tool, I have used <a href="http://www.omegat.org/zh_CN/omegat.html">OmegaT</a> to make and follow the latest translation. To translate the spec into Japanese language, running following steps (these steps seems to be primitive way):

1. Download the latest spec (https://html.spec.whatwg.org/multipage/*)
1. (Processing the HTML for OmegaT, because OmegaT's HTML parser has some bugs. You can use instead <a href="http://okapiframework.org/wiki/index.php?title=Okapi_Filters_Plugin_for_OmegaT">okapi Filters</a>.)
1. Translate changed sentences on OmegaT
1. Output translated HTML files
1. Push these HTML files to GitHub

You can also use various translation memory application, please see <a href="https://zh.wikipedia.org/wiki/%E9%9B%BB%E8%85%A6%E8%BC%94%E5%8A%A9%E7%BF%BB%E8%AD%AF">電腦輔助翻譯</a> on Chinese Wikipedia.

**Comment by momdo** [comment]
I close this issue, since there is no response.
